-- MySQL Script generated by MySQL Workbench
-- Mon May 26 19:33:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; -- CORREGIDO: Eliminado el doble 'FOREIGN_KEY'
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jugador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jugador` (
  `idJugador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Edad` VARCHAR(45) NULL DEFAULT NULL,
  `Pais` VARCHAR(45) NULL DEFAULT NULL,
  `Posicion` VARCHAR(45) NULL DEFAULT NULL,
  `Precio` INT NULL DEFAULT NULL,
  `idEquipo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idJugador`),
  INDEX `idx_Jugador_idEquipo` (`idEquipo` ASC) VISIBLE,
  UNIQUE INDEX `uq_Jugador_idJugador_idEquipo` (`idJugador`, `idEquipo`) VISIBLE,
  CONSTRAINT `fk_Jugador_Equipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `mydb`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temporada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Temporada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Temporada` (
  `idTemporada` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idTemporada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jornada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jornada` (
  `idJornada` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `idTemporada` INT NOT NULL,
  PRIMARY KEY (`idJornada`),
  INDEX `idx_Jornada_idTemporada` (`idTemporada` ASC) VISIBLE,
  CONSTRAINT `fk_Jornada_Temporada`
    FOREIGN KEY (`idTemporada`)
    REFERENCES `mydb`.`Temporada` (`idTemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Partido` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `idJornada` INT NULL DEFAULT NULL,
  `idEquipoLocal` INT NULL DEFAULT NULL,
  `idEquipoVisitante` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `idx_Partido_idJornada` (`idJornada` ASC) VISIBLE,
  INDEX `idx_Partido_idEquipoLocal` (`idEquipoLocal` ASC) VISIBLE,
  INDEX `idx_Partido_idEquipoVisitante` (`idEquipoVisitante` ASC) VISIBLE,
  UNIQUE INDEX `uq_Partido_idPartido_idJornada` (`idPartido`, `idJornada` ASC) VISIBLE,
  CONSTRAINT `fk_Partido_Jornada`
    FOREIGN KEY (`idJornada`)
    REFERENCES `mydb`.`Jornada` (`idJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_EquipoLocal`
    FOREIGN KEY (`idEquipoLocal`)
    REFERENCES `mydb`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_EquipoVisitante`
    FOREIGN KEY (`idEquipoVisitante`)
    REFERENCES `mydb`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estadisticas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estadisticas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estadisticas` (
  `idEstadisticas` INT NOT NULL AUTO_INCREMENT,
  `idPartido` INT NULL DEFAULT NULL,
  `idJornada` INT NULL DEFAULT NULL,
  `idJugador` INT NULL DEFAULT NULL,
  `idEquipo` INT NULL DEFAULT NULL,
  `Minutos` INT NULL,
  `Goles` INT NULL,
  `Asistencias` INT NULL,
  `TirosPenalti` INT NULL,
  `TirosPenaltiIntentados` INT NULL,
  `Disparos` INT NULL,
  `DisparosPorteria` INT NULL,
  `TarjetasAmarillas` INT NULL,
  `TarjetasRojas` INT NULL,
  `Toques` INT NULL,
  `Entradas` INT NULL,
  `Intercepciones` INT NULL,
  `Bloqueos` INT NULL,
  `GolesEsperados` FLOAT NULL,
  `GolesEsperadosSinPenaltis` FLOAT NULL,
  `AsistenciasEsperadas` FLOAT NULL,
  `AccionesCreadasDeTiro` INT NULL,
  `AccionesCreadasDeGol` INT NULL,
  `PasesCompletados` INT NULL,
  `PasesIntentados` INT NULL,
  `PorcentajePasesCompletados` FLOAT NULL,
  `PasesProgresivos` INT NULL,
  `Controles` INT NULL,
  `ConduccionesProgresivas` INT NULL,
  `EntradasOfensivas` INT NULL,
  `EntradasConExito` INT NULL,
  PRIMARY KEY (`idEstadisticas`),
  INDEX `idx_Estadisticas_PartidoJornada` (`idPartido` ASC, `idJornada` ASC) VISIBLE,
  INDEX `idx_Estadisticas_JugadorEquipo` (`idJugador` ASC, `idEquipo` ASC) VISIBLE,
  CONSTRAINT `fk_Estadisticas_Partido`
    FOREIGN KEY (`idPartido` , `idJornada`)
    REFERENCES `mydb`.`Partido` (`idPartido` , `idJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estadisticas_JugadorEquipo`
    FOREIGN KEY (`idJugador` , `idEquipo`)
    REFERENCES `mydb`.`Jugador` (`idJugador` , `idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `idGoogle` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NULL,
  `esAdmin` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`idManager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plantilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Plantilla` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Plantilla` (
  `idPlantilla` INT NOT NULL AUTO_INCREMENT,
  `Alineacion` VARCHAR(45) NULL DEFAULT NULL,
  `Puntos` INT NULL DEFAULT NULL,
  `idJornada` INT NULL DEFAULT NULL,
  `idManager` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPlantilla`),
  INDEX `idx_Plantilla_idJornada` (`idJornada` ASC) VISIBLE,
  INDEX `idx_Plantilla_idManager` (`idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Plantilla_Jornada`
    FOREIGN KEY (`idJornada`)
    REFERENCES `mydb`.`Jornada` (`idJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plantilla_Manager`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Objetos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Objetos` (
  `idObjetos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Precio` INT NULL DEFAULT NULL,
  `Descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idObjetos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ligas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ligas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ligas` (
  `idLigas` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLigas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participaciones` (
  `idManager` INT NOT NULL,
  `idLigas` INT NOT NULL,
  PRIMARY KEY (`idManager`, `idLigas`),
  INDEX `idx_Participaciones_idLigas` (`idLigas` ASC) VISIBLE,
  INDEX `idx_Participaciones_idManager` (`idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Participaciones_Manager`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participaciones_Ligas`
    FOREIGN KEY (`idLigas`)
    REFERENCES `mydb`.`Ligas` (`idLigas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CartaObjeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CartaObjeto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CartaObjeto` (
  `idCartaObjeto` INT NOT NULL AUTO_INCREMENT,
  `idObjetos` INT NOT NULL,
  `idManager` INT NOT NULL,
  `Rareza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCartaObjeto`),
  INDEX `idx_CartaObjeto_idObjetos` (`idObjetos` ASC) VISIBLE,
  INDEX `idx_CartaObjeto_idManager` (`idManager` ASC) VISIBLE,
  UNIQUE INDEX `idCartaObjeto_UNIQUE` (`idCartaObjeto` ASC) VISIBLE,
  CONSTRAINT `fk_CartaObjeto_Objetos`
    FOREIGN KEY (`idObjetos`)
    REFERENCES `mydb`.`Objetos` (`idObjetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartaObjeto_Manager`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CartaJugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CartaJugador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CartaJugador` (
  `idCartaJugador` INT NOT NULL,
  `Jugador_idJugador` INT NOT NULL,
  `Manager_idManager` INT NOT NULL,
  PRIMARY KEY (`idCartaJugador`),
  INDEX `idx_CartaJugador_Jugador` (`Jugador_idJugador` ASC) VISIBLE,
  INDEX `idx_CartaJugador_Manager` (`Manager_idManager` ASC) VISIBLE,
  CONSTRAINT `fk_CartaJugador_Jugador`
    FOREIGN KEY (`Jugador_idJugador`)
    REFERENCES `mydb`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartaJugador_Manager`
    FOREIGN KEY (`Manager_idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlantillaJugadorObjeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlantillaJugadorObjeto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PlantillaJugadorObjeto` (
  `idPlantilla` INT NOT NULL,
  `idCartaObjeto` INT NOT NULL,
  `idCartaJugador` INT NOT NULL,
  INDEX `idx_PlantillaJugadorObjeto_Plantilla` (`idPlantilla` ASC) VISIBLE,
  PRIMARY KEY (`idPlantilla`, `idCartaObjeto`, `idCartaJugador`),
  INDEX `idx_PlantillaJugadorObjeto_CartaObjeto` (`idCartaObjeto` ASC) VISIBLE,
  INDEX `idx_PlantillaJugadorObjeto_CartaJugador` (`idCartaJugador` ASC) VISIBLE,
  CONSTRAINT `fk_PlantillaJugadorObjeto_Plantilla`
    FOREIGN KEY (`idPlantilla`)
    REFERENCES `mydb`.`Plantilla` (`idPlantilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlantillaJugadorObjeto_CartaObjeto`
    FOREIGN KEY (`idCartaObjeto`)
    REFERENCES `mydb`.`CartaObjeto` (`idCartaObjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlantillaJugadorObjeto_CartaJugador`
    FOREIGN KEY (`idCartaJugador`)
    REFERENCES `mydb`.`CartaJugador` (`idCartaJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;